# apiVersion: v1
# kind: Service
# metadata:
#   annotations:
#     prometheus.io/scrape: 'true'
#     prometheus.io/path: '/metrics'
#     prometheus.io/port: '9100'
#   labels:
#     app: node-exporter
#   name: node-exporter
# spec:
#   type: ClusterIP
#   clusterIP: None
#   ports:
#   - port: 9100
#     protocol: TCP
#     targetPort: 9100
#   selector:
#     app: node-exporter

# ---

# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: node-exporter
# spec:
#   selector:
#     matchLabels:
#       app: node-exporter
#   template:
#     metadata:
#       labels:
#         app: node-exporter
#       name: node-exporter
#     spec:
#       containers:
#       - image: prom/node-exporter
#         name: node-exporter
#         ports:
#         - containerPort: 9100
#           hostPort: 9100
#       hostNetwork: true
#       hostPID: true